version: "2"
services:
  playground:
    image: xavi/playground
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    ports:
      - 80:80
    environment:
      - ALLOW_OVERRIDE=true
